config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  post 'information/import_custom_data'
  get 'information/index'
  get 'information/delete_information'

  root to: 'home#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/information.rb
class Information < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/controllers/information_controller.rb
class InformationController < ApplicationController
  def import_custom_data

    uploaded_file = params[:csv_file]
    
    file_path = Rails.root.join('tmp', 'uploads', "#{Time.now.to_i}_#{uploaded_file.original_filename}")
    
    name = File.basename(file_path)

    File.open(file_path, 'wb') do |file|
      file.write(uploaded_file.read)
    end
    
    system("rake import:import_csv['#{name}']")

    flash[:success] = "Information was successfully Imported."
    redirect_to information_index_path
  end

  def index
    @informations = Information.all
  end

  def delete_information
    Information.destroy_all
    
    flash[:success] = "Information was successfully Deleted."
    redirect_to home_index_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Home Page</title>
  </head>
  <body>
    <h1>This is landing page</h1>

    <% if Information.count == 0 %>
      <%= form_tag(information_import_custom_data_path, multipart: true) do %>
        <%= file_field_tag :csv_file %>
        <%= submit_tag "Upload", :class=>"btn btn-primary" %>
      <% end %>
    <% else %>
      <%= link_to "Delete Previously Imported Data", information_delete_information_path, class: "btn btn-danger" %>
    <% end %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <!-- Added Bootstrap cdns -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>